config/routes.rb
Rails.application.routes.draw do
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
  has_many :classlists, dependent: :destroy
  has_many :sections, through: :classlists, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, notice: "Student was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.expect(student: [ :name, :year_level, :program, :department_id ])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year_level, style: "display: block" %>
    <%= form.number_field :year_level %>
  </div>

  <div>
    <%= form.label :program, style: "display: block" %>
    <%= form.text_field :program %>
  </div>

  <div>
    <%= form.label :department_id, "Department", style: "display: block" %>
    <%= form.collection_select :department_id, Department.all, :id, :name, prompt: "Select a department" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Year level:</strong>
    <%= student.year_level %>
  </p>

  <p>
    <strong>Program:</strong>
    <%= student.program %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= student.department.name %>
  </p>

</div>

app/views/students/edit.html.erb
<% content_for :title, "Editing student" %>

<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Students" %>

<h1>List of Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year Level</th>
      <th>Program</th>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name%></td>
        <td><%= student.year_level%></td>
        <td><%= student.program%></td>
        <td><%= student.department.name%></td>
        <td><%= link_to "Show this student",student %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<% content_for :title, "New student" %>

<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<h3>List of Subjects:</h3>

<table>
  <thead>
    <tr>
      <th>Section</th>
      <th>Subject</th>
      <th>Teacher</th>
    </tr>
  </thead>
  <tbody>
    <% @student.classlists.each do |classlist| %>
      <tr>
        <td><%= classlist.section.name%></td>
        <td><%= classlist.section.subject.name%></td>
        <td><%= classlist.section.subject.teacher.name%></td>
      </tr>
    <% end %>
  </tbody>
</table>


<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>