config/routes.rb
Rails.application.routes.draw do
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :subject
  has_many :classlists, dependent: :destroy
  has_many :students, through: :classlists, dependent: :destroy
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: "Section was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy!

    respond_to do |format|
      format.html { redirect_to sections_path, notice: "Section was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.expect(section: [ :name, :room, :time_slot, :subject_id ])
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :room, style: "display: block" %>
    <%= form.text_field :room %>
  </div>

  <div>
    <%= form.label :time_slot, style: "display: block" %>
    <%= form.text_field :time_slot %>
  </div>

  <div>
    <%= form.label :subject_id, "Subject",  style: "display: block" %>
    <%= form.collection_select :subject_id, Subject.all, :id, :name, prompt: "Select a subject" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
  <p>
    <strong>Name:</strong>
    <%= section.name %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= section.room %>
  </p>

  <p>
    <strong>Time slot:</strong>
    <%= section.time_slot %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= section.subject.name %>
  </p>

</div>

app/views/sections/edit.html.erb
<% content_for :title, "Editing section" %>

<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to sections", sections_path %>
</div>

app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Sections" %>

<h1>List of Sections</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Room</th>
      <th>Time Slot</th>
      <th>Subject</th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name%></td>
        <td><%= section.room%></td>
        <td><%= section.time_slot%></td>
        <td><%= section.subject.name%></td>
        <td><%= link_to "Show this section",section %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New section", new_section_path %>

app/views/sections/new.html.erb
<% content_for :title, "New section" %>

<h1>New section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Back to sections", sections_path %>
</div>

app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>

<div>
  <%= link_to "Edit this section", edit_section_path(@section) %> |
  <%= link_to "Back to sections", sections_path %>

  <%= button_to "Destroy this section", @section, method: :delete %>
</div>