config/routes.rb
Rails.application.routes.draw do
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher
  has_many :sections, dependent: :destroy
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: "Subject was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy!

    respond_to do |format|
      format.html { redirect_to subjects_path, notice: "Subject was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.expect(subject: [ :name, :teacher_id ])
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :teacher_id, "Teacher", style: "display: block" %>
    <%= form.collection_select :teacher_id, Teacher.all, :id, :name, promt: "Select a teacher" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <p>
    <strong>Name:</strong>
    <%= subject.name %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= subject.teacher.name %>
  </p>

</div>

app/views/subjects/edit.html.erb
<% content_for :title, "Editing subject" %>

<h1>Editing subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Show this subject", @subject %> |
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Subjects" %>

<h1>List of Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Teacher</th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name%></td>
        <td><%= subject.teacher.name%></td>
        <td><%= link_to "Show this subject", subject %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New subject", new_subject_path %>

app/views/subjects/new.html.erb
<% content_for :title, "New subject" %>

<h1>New subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subject %>


<% @subject.sections.each do | section | %>
  <h3>Section: <%= section.name  %> Room <%= section.room  %> Time Slot: <%= section.time_slot %></h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Program</th>
      <th>Year Level</th>
    </tr>
  </thead>
  <tbody>
    <% section.classlists.each do |classlist| %>
      <tr>
        <td><%= classlist.student.name%></td>
        <td><%= classlist.student.program%></td>
        <td><%= classlist.student.year_level%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>


<div>
  <%= link_to "Edit this subject", edit_subject_path(@subject) %> |
  <%= link_to "Back to subjects", subjects_path %>

  <%= button_to "Destroy this subject", @subject, method: :delete %>
</div>