config/routes.rb
Rails.application.routes.draw do
  resources :classlists
  resources :sections
  resources :subjects
  resources :teachers
  resources :students
  resources :departments
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :subjects, dependent: :destroy
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: "Teacher was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy!

    respond_to do |format|
      format.html { redirect_to teachers_path, notice: "Teacher was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.expect(teacher: [ :name, :email, :specialization, :status, :department_id ])
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :specialization, style: "display: block" %>
    <%= form.text_field :specialization %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :department_id, style: "display: block" %>
    <%= form.text_field :department_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p>
    <strong>Name:</strong>
    <%= teacher.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= teacher.email %>
  </p>

  <p>
    <strong>Specialization:</strong>
    <%= teacher.specialization %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= teacher.status %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= teacher.department.name %>
  </p>

</div>

app/views/teachers/edit.html.erb
<% content_for :title, "Editing teacher" %>

<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Teachers" %>

<h1>List of Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Specialization</th>
      <th>Status</th>
      <th>Show</th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name%></td>
        <td><%= teacher.email%></td>
        <td><%= teacher.specialization%></td>
        <td><%= teacher.status%></td>
        <td><%= link_to "Show this teacher", teacher %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<% content_for :title, "New teacher" %>

<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>


<h3>List of Subjects:</h3>
<table>
  <thead>
    <tr>
      <th>Section</th>
      <th>Subject</th>
      <th>Room</th>
      <th>Time Slot</th>
    </tr>
  </thead>
  <tbody>
    <% @teacher.subjects.each do |subject| %>
      <% subject.sections.each do |section| %>
      <tr>
        <td><%= section.name%></td>
        <td><%= section.subject.name%></td>
        <td><%= section.room%></td>
        <td><%= section.time_slot%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<div>
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
</div>